{$mode objfpc}

unit mono_row_indexes;

interface

{*
* The last entry in the enum is used to give the number
* of columns in the row.
*}

type
  _MONO_ASSEMBLY =  Longint;
const
  MONO_ASSEMBLY_HASH_ALG = 0;
  MONO_ASSEMBLY_MAJOR_VERSION = 1;
  MONO_ASSEMBLY_MINOR_VERSION = 2;
  MONO_ASSEMBLY_BUILD_NUMBER = 3;
  MONO_ASSEMBLY_REV_NUMBER = 4;
  MONO_ASSEMBLY_FLAGS = 5;
  MONO_ASSEMBLY_PUBLIC_KEY = 6;
  MONO_ASSEMBLY_NAME = 7;
  MONO_ASSEMBLY_CULTURE = 8;
  MONO_ASSEMBLY_SIZE = 9;


type
  _MONO_ASSEMBLYOS =  Longint;
const
  MONO_ASSEMBLYOS_PLATFORM = 0;
  MONO_ASSEMBLYOS_MAJOR_VERSION = 1;
  MONO_ASSEMBLYOS_MINOR_VERSION = 2;
  MONO_ASSEMBLYOS_SIZE = 3;


type
  _MONO_ASSEMBLY_PROCESSOR =  Longint;
const
  MONO_ASSEMBLY_PROCESSOR = 0;
  MONO_ASSEMBLY_PROCESSOR_SIZE = 1;


type
  _MONO_ASSEMBLYREF =  Longint;
const
  MONO_ASSEMBLYREF_MAJOR_VERSION = 0;
  MONO_ASSEMBLYREF_MINOR_VERSION = 1;
  MONO_ASSEMBLYREF_BUILD_NUMBER = 2;
  MONO_ASSEMBLYREF_REV_NUMBER = 3;
  MONO_ASSEMBLYREF_FLAGS = 4;
  MONO_ASSEMBLYREF_PUBLIC_KEY = 5;
  MONO_ASSEMBLYREF_NAME = 6;
  MONO_ASSEMBLYREF_CULTURE = 7;
  MONO_ASSEMBLYREF_HASH_VALUE = 8;
  MONO_ASSEMBLYREF_SIZE = 9;


type
  _MONO_ASSEMBLYREFOS =  Longint;
const
  MONO_ASSEMBLYREFOS_PLATFORM = 0;
  MONO_ASSEMBLYREFOS_MAJOR_VERSION = 1;
  MONO_ASSEMBLYREFOS_MINOR_VERSION = 2;
  MONO_ASSEMBLYREFOS_ASSEMBLYREF = 3;
  MONO_ASSEMBLYREFOS_SIZE = 4;


type
  _MONO_ASSEMBLYREFPROC =  Longint;
const
  MONO_ASSEMBLYREFPROC_PROCESSOR = 0;
  MONO_ASSEMBLYREFPROC_ASSEMBLYREF = 1;
  MONO_ASSEMBLYREFPROC_SIZE = 2;


type
_MONO_CLASS_LAYOUT =  Longint;
const
  MONO_CLASS_LAYOUT_PACKING_SIZE = 0;
  MONO_CLASS_LAYOUT_CLASS_SIZE = 1;
  MONO_CLASS_LAYOUT_PARENT = 2;
  MONO_CLASS_LAYOUT_SIZE = 3;


type
  _MONO_CONSTANT =  Longint;
const
  MONO_CONSTANT_TYPE = 0;
  MONO_CONSTANT_PADDING = 1;
  MONO_CONSTANT_PARENT = 2;
  MONO_CONSTANT_VALUE = 3;
  MONO_CONSTANT_SIZE = 4;


type
  _MONO_CUSTOM_ATTR =  Longint;
const
  MONO_CUSTOM_ATTR_PARENT = 0;
  MONO_CUSTOM_ATTR_TYPE = 1;
  MONO_CUSTOM_ATTR_VALUE = 2;
  MONO_CUSTOM_ATTR_SIZE = 3;


type
  _MONO_DECL_SECURITY =  Longint;
const
  MONO_DECL_SECURITY_ACTION = 0;
  MONO_DECL_SECURITY_PARENT = 1;
  MONO_DECL_SECURITY_PERMISSIONSET = 2;
  MONO_DECL_SECURITY_SIZE = 3;


type
  _MONO_EVENT_MAP =  Longint;
const
  MONO_EVENT_MAP_PARENT = 0;
  MONO_EVENT_MAP_EVENTLIST = 1;
  MONO_EVENT_MAP_SIZE = 2;


type
  _MONO_EVENT =  Longint;
const
  MONO_EVENT_FLAGS = 0;
  MONO_EVENT_NAME = 1;
  MONO_EVENT_TYPE = 2;
  MONO_EVENT_SIZE = 3;


type
  _MONO_EVENT_POINTER =  Longint;
const
  MONO_EVENT_POINTER_EVENT = 0;
  MONO_EVENT_POINTER_SIZE = 1;


type
  _MONO_EXP_TYPE =  Longint;
const
  MONO_EXP_TYPE_FLAGS = 0;
  MONO_EXP_TYPE_TYPEDEF = 1;
  MONO_EXP_TYPE_NAME = 2;
  MONO_EXP_TYPE_NAMESPACE = 3;
  MONO_EXP_TYPE_IMPLEMENTATION = 4;
  MONO_EXP_TYPE_SIZE = 5;


type
  _MONO_FIELD =  Longint;
const
  MONO_FIELD_FLAGS = 0;
  MONO_FIELD_NAME = 1;
  MONO_FIELD_SIGNATURE = 2;
  MONO_FIELD_SIZE = 3;


type
  _MONO_FIELD_LAYOUT =  Longint;
const
  MONO_FIELD_LAYOUT_OFFSET = 0;
  MONO_FIELD_LAYOUT_FIELD = 1;
  MONO_FIELD_LAYOUT_SIZE = 2;


type
  _MONO_FIELD_MARSHAL =  Longint;
const
  MONO_FIELD_MARSHAL_PARENT = 0;
  MONO_FIELD_MARSHAL_NATIVE_TYPE = 1;
  MONO_FIELD_MARSHAL_SIZE = 2;


type
  _MONO_FIELD_POINTER =  Longint;
const
  MONO_FIELD_POINTER_FIELD = 0;
  MONO_FIELD_POINTER_SIZE = 1;


type
  _MONO_FIELD_RVA =  Longint;
const
  MONO_FIELD_RVA_RVA = 0;
  MONO_FIELD_RVA_FIELD = 1;
  MONO_FIELD_RVA_SIZE = 2;


type
  _MONO_FILE =  Longint;
const
  MONO_FILE_FLAGS = 0;
  MONO_FILE_NAME = 1;
  MONO_FILE_HASH_VALUE = 2;
  MONO_FILE_SIZE = 3;


type
  _MONO_IMPLMAP =  Longint;
const
  MONO_IMPLMAP_FLAGS = 0;
  MONO_IMPLMAP_MEMBER = 1;
  MONO_IMPLMAP_NAME = 2;
  MONO_IMPLMAP_SCOPE = 3;
  MONO_IMPLMAP_SIZE = 4;


type
  _MONO_INTERFACEIMPL =  Longint;
const
  MONO_INTERFACEIMPL_CLASS = 0;
  MONO_INTERFACEIMPL_INTERFACE = 1;
  MONO_INTERFACEIMPL_SIZE = 2;


type
  _MONO_MANIFEST =  Longint;
const
  MONO_MANIFEST_OFFSET = 0;
  MONO_MANIFEST_FLAGS = 1;
  MONO_MANIFEST_NAME = 2;
  MONO_MANIFEST_IMPLEMENTATION = 3;
  MONO_MANIFEST_SIZE = 4;


type
  _MONO_MEMBERREF =  Longint;
const
  MONO_MEMBERREF_CLASS = 0;
  MONO_MEMBERREF_NAME = 1;
  MONO_MEMBERREF_SIGNATURE = 2;
  MONO_MEMBERREF_SIZE = 3;


type
  _MONO_METHOD =  Longint;
const
  MONO_METHOD_RVA = 0;
  MONO_METHOD_IMPLFLAGS = 1;
  MONO_METHOD_FLAGS = 2;
  MONO_METHOD_NAME = 3;
  MONO_METHOD_SIGNATURE = 4;
  MONO_METHOD_PARAMLIST = 5;
  MONO_METHOD_SIZE = 6;


type
  _MONO_METHODIMPL =  Longint;
const
  MONO_METHODIMPL_CLASS = 0;
  MONO_METHODIMPL_BODY = 1;
  MONO_METHODIMPL_DECLARATION = 2;
  MONO_METHODIMPL_SIZE = 3;


type
  _MONO_METHOD_POINTER =  Longint;
const
  MONO_METHOD_POINTER_METHOD = 0;
  MONO_METHOD_POINTER_SIZE = 1;


type
  _MONO_METHOD_SEMA =  Longint;
const
  MONO_METHOD_SEMA_SEMANTICS = 0;
  MONO_METHOD_SEMA_METHOD = 1;
  MONO_METHOD_SEMA_ASSOCIATION = 2;
  MONO_METHOD_SEMA_SIZE = 3;


type
  _MONO_MODULE =  Longint;
const
  MONO_MODULE_GENERATION = 0;
  MONO_MODULE_NAME = 1;
  MONO_MODULE_MVID = 2;
  MONO_MODULE_ENC = 3;
  MONO_MODULE_ENCBASE = 4;
  MONO_MODULE_SIZE = 5;


type
  _MONO_MODULEREF =  Longint;
const
  MONO_MODULEREF_NAME = 0;
  MONO_MODULEREF_SIZE = 1;


type
  _MONO_NESTED_CLASS =  Longint;
const
  MONO_NESTED_CLASS_NESTED = 0;
  MONO_NESTED_CLASS_ENCLOSING = 1;
  MONO_NESTED_CLASS_SIZE = 2;


type
  _MONO_PARAM =  Longint;
const
  MONO_PARAM_FLAGS = 0;
  MONO_PARAM_SEQUENCE = 1;
  MONO_PARAM_NAME = 2;
  MONO_PARAM_SIZE = 3;


type
  _MONO_PARAM_POINTER =  Longint;
const
  MONO_PARAM_POINTER_PARAM = 0;
  MONO_PARAM_POINTER_SIZE = 1;


type
  _MONO_PROPERTY =  Longint;
const
  MONO_PROPERTY_FLAGS = 0;
  MONO_PROPERTY_NAME = 1;
  MONO_PROPERTY_TYPE = 2;
  MONO_PROPERTY_SIZE = 3;


type
  _MONO_PROPERTY_POINTER =  Longint;
const
  MONO_PROPERTY_POINTER_PROPERTY = 0;
  MONO_PROPERTY_POINTER_SIZE = 1;


type
  _MONO_PROPERTY_MAP =  Longint;
const
  MONO_PROPERTY_MAP_PARENT = 0;
  MONO_PROPERTY_MAP_PROPERTY_LIST = 1;
  MONO_PROPERTY_MAP_SIZE = 2;


type
  _MONO_STAND_ALONE =  Longint;
const
  MONO_STAND_ALONE_SIGNATURE = 0;
  MONO_STAND_ALONE_SIGNATURE_SIZE = 1;


type
  _MONO_TYPEDEF =  Longint;
const
  MONO_TYPEDEF_FLAGS = 0;
  MONO_TYPEDEF_NAME = 1;
  MONO_TYPEDEF_NAMESPACE = 2;
  MONO_TYPEDEF_EXTENDS = 3;
  MONO_TYPEDEF_FIELD_LIST = 4;
  MONO_TYPEDEF_METHOD_LIST = 5;
  MONO_TYPEDEF_SIZE = 6;


type
  _MONO_TYPEREF =  Longint;
const
  MONO_TYPEREF_SCOPE = 0;
  MONO_TYPEREF_NAME = 1;
  MONO_TYPEREF_NAMESPACE = 2;
  MONO_TYPEREF_SIZE = 3;


type
  _MONO_TYPESPEC =  Longint;
const
  MONO_TYPESPEC_SIGNATURE = 0;
  MONO_TYPESPEC_SIZE = 1;


type
  _MONO_GENERICPARAM =  Longint;
const
  MONO_GENERICPARAM_NUMBER = 0;
  MONO_GENERICPARAM_FLAGS = 1;
  MONO_GENERICPARAM_OWNER = 2;
  MONO_GENERICPARAM_NAME = 3;
  MONO_GENERICPARAM_SIZE = 4;


type
  _MONO_METHODSPEC =  Longint;
const
  MONO_METHODSPEC_METHOD = 0;
  MONO_METHODSPEC_SIGNATURE = 1;
  MONO_METHODSPEC_SIZE = 2;


type
  _MONO_GENPARCONSTRAINT =  Longint;
const
  MONO_GENPARCONSTRAINT_GENERICPAR = 0;
  MONO_GENPARCONSTRAINT_CONSTRAINT = 1;
  MONO_GENPARCONSTRAINT_SIZE = 2;


type
  _MONO_DOCUMENT =  Longint;
const
  MONO_DOCUMENT_NAME = 0;
  MONO_DOCUMENT_HASHALG = 1;
  MONO_DOCUMENT_HASH = 2;
  MONO_DOCUMENT_LANGUAGE = 3;
  MONO_DOCUMENT_SIZE = 4;


type
  _MONO_METHODBODY =  Longint;
const
  MONO_METHODBODY_DOCUMENT = 0;
  MONO_METHODBODY_SEQ_POINTS = 1;
  MONO_METHODBODY_SIZE = 2;


type
  _MONO_LOCALSCOPE =  Longint;
const
  MONO_LOCALSCOPE_METHOD = 0;
  MONO_LOCALSCOPE_IMPORTSCOPE = 1;
  MONO_LOCALSCOPE_VARIABLELIST = 2;
  MONO_LOCALSCOPE_CONSTANTLIST = 3;
  MONO_LOCALSCOPE_STARTOFFSET = 4;
  MONO_LOCALSCOPE_LENGTH = 5;
  MONO_LOCALSCOPE_SIZE = 6;


type
  _MONO_LOCALVARIABLE =  Longint;
const
  MONO_LOCALVARIABLE_ATTRIBUTES = 0;
  MONO_LOCALVARIABLE_INDEX = 1;
  MONO_LOCALVARIABLE_NAME = 2;
  MONO_LOCALVARIABLE_SIZE = 3;

{
* Coded Tokens
* The _BITS entry is for the bits used in the token.
* The _MASK entry is for mask the index out.
}

type
  _MONO_TYPEDEFORREF =  Longint;
const
  MONO_TYPEDEFORREF_TYPEDEF = 0;
  MONO_TYPEDEFORREF_TYPEREF = 1;
  MONO_TYPEDEFORREF_TYPESPEC = 2;
  MONO_TYPEDEFORREF_BITS = 2;
  MONO_TYPEDEFORREF_MASK = 3;


type
  _MONO_HASCONSTANT =  Longint;
const
  MONO_HASCONSTANT_FIEDDEF = 0;
  MONO_HASCONSTANT_PARAM = 1;
  MONO_HASCONSTANT_PROPERTY = 2;
  MONO_HASCONSTANT_BITS = 2;
  MONO_HASCONSTANT_MASK = 3;


type
  _MONO_CUSTOM_ATTR_FLAGS =  Longint;
const
  MONO_CUSTOM_ATTR_METHODDEF = 0;
  MONO_CUSTOM_ATTR_FIELDDEF = 1;
  MONO_CUSTOM_ATTR_TYPEREF = 2;
  MONO_CUSTOM_ATTR_TYPEDEF = 3;
  MONO_CUSTOM_ATTR_PARAMDEF = 4;
  MONO_CUSTOM_ATTR_INTERFACE = 5;
  MONO_CUSTOM_ATTR_MEMBERREF = 6;
  MONO_CUSTOM_ATTR_MODULE = 7;
  MONO_CUSTOM_ATTR_PERMISSION = 8;
  MONO_CUSTOM_ATTR_PROPERTY = 9;
  MONO_CUSTOM_ATTR_EVENT = 10;
  MONO_CUSTOM_ATTR_SIGNATURE = 11;
  MONO_CUSTOM_ATTR_MODULEREF = 12;
  MONO_CUSTOM_ATTR_TYPESPEC = 13;
  MONO_CUSTOM_ATTR_ASSEMBLY = 14;
  MONO_CUSTOM_ATTR_ASSEMBLYREF = 15;
  MONO_CUSTOM_ATTR_FILE = 16;
  MONO_CUSTOM_ATTR_EXP_TYPE = 17;
  MONO_CUSTOM_ATTR_MANIFEST = 18;
  MONO_CUSTOM_ATTR_GENERICPAR = 19;
  MONO_CUSTOM_ATTR_BITS = 5;
  MONO_CUSTOM_ATTR_MASK = $1F;


type
  _MONO_HAS_FIELD_MARSHAL =  Longint;
const
  MONO_HAS_FIELD_MARSHAL_FIELDSREF = 0;
  MONO_HAS_FIELD_MARSHAL_PARAMDEF = 1;
  MONO_HAS_FIELD_MARSHAL_BITS = 1;
  MONO_HAS_FIELD_MARSHAL_MASK = 1;


type
  _MONO_HAS_DECL_SECURITY =  Longint;
const
  MONO_HAS_DECL_SECURITY_TYPEDEF = 0;
  MONO_HAS_DECL_SECURITY_METHODDEF = 1;
  MONO_HAS_DECL_SECURITY_ASSEMBLY = 2;
  MONO_HAS_DECL_SECURITY_BITS = 2;
  MONO_HAS_DECL_SECURITY_MASK = 3;

type
  _MONO_MEMBERREF_PARENT =  Longint;
const
  MONO_MEMBERREF_PARENT_TYPEDEF = 0;
  MONO_MEMBERREF_PARENT_TYPEREF = 1;
  MONO_MEMBERREF_PARENT_MODULEREF = 2;
  MONO_MEMBERREF_PARENT_METHODDEF = 3;
  MONO_MEMBERREF_PARENT_TYPESPEC = 4;
  MONO_MEMBERREF_PARENT_BITS = 3;
  MONO_MEMBERREF_PARENT_MASK = 7;


type
  _MONO_HAS_SEMANTICS =  Longint;
const
  MONO_HAS_SEMANTICS_EVENT = 0;
  MONO_HAS_SEMANTICS_PROPERTY = 1;
  MONO_HAS_SEMANTICS_BITS = 1;
  MONO_HAS_SEMANTICS_MASK = 1;


type
  _MONO_METHODDEFORREF =  Longint;
const
  MONO_METHODDEFORREF_METHODDEF = 0;
  MONO_METHODDEFORREF_METHODREF = 1;
  MONO_METHODDEFORREF_BITS = 1;
  MONO_METHODDEFORREF_MASK = 1;


type
  _MONO_MEMBERFORWD =  Longint;
const
  MONO_MEMBERFORWD_FIELDDEF = 0;
  MONO_MEMBERFORWD_METHODDEF = 1;
  MONO_MEMBERFORWD_BITS = 1;
  MONO_MEMBERFORWD_MASK = 1;


type
  _MONO_IMPLEMENTATION =  Longint;
const
  MONO_IMPLEMENTATION_FILE = 0;
  MONO_IMPLEMENTATION_ASSEMBLYREF = 1;
  MONO_IMPLEMENTATION_EXP_TYPE = 2;
  MONO_IMPLEMENTATION_BITS = 2;
  MONO_IMPLEMENTATION_MASK = 3;

type
  _MONO_CUSTOM_ATTR_TYPE =  Longint;
const
  MONO_CUSTOM_ATTR_TYPE_TYPEREF = 0;
  MONO_CUSTOM_ATTR_TYPE_TYPEDEF = 1;
  MONO_CUSTOM_ATTR_TYPE_METHODDEF = 2;
  MONO_CUSTOM_ATTR_TYPE_MEMBERREF = 3;
  MONO_CUSTOM_ATTR_TYPE_STRING = 4;
  MONO_CUSTOM_ATTR_TYPE_BITS = 3;
  MONO_CUSTOM_ATTR_TYPE_MASK = 7;


type
  _MONO_RESOLUTION_SCOPE =  Longint;
const
  MONO_RESOLUTION_SCOPE_MODULE = 0;
  MONO_RESOLUTION_SCOPE_MODULEREF = 1;
  MONO_RESOLUTION_SCOPE_ASSEMBLYREF = 2;
  MONO_RESOLUTION_SCOPE_TYPEREF = 3;
  MONO_RESOLUTION_SCOPE_BITS = 2;
  MONO_RESOLUTION_SCOPE_MASK = 3;

  { Kept for compatibility since this is a public header file  }

type
  _MONO_RESOLTION_SCOPE =  Longint;
const
  MONO_RESOLTION_SCOPE_MODULE = 0;
  MONO_RESOLTION_SCOPE_MODULEREF = 1;
  MONO_RESOLTION_SCOPE_ASSEMBLYREF = 2;
  MONO_RESOLTION_SCOPE_TYPEREF = 3;
  MONO_RESOLTION_SCOPE_BITS = 2;
  MONO_RESOLTION_SCOPE_MASK = 3;


type
  _MONO_TYPEORMETHOD =  Longint;
const
  MONO_TYPEORMETHOD_TYPE = 0;
  MONO_TYPEORMETHOD_METHOD = 1;
  MONO_TYPEORMETHOD_BITS = 1;
  MONO_TYPEORMETHOD_MASK = 1;



implementation

end.
