{*
* blob.h: Definitions used to pull information out of the Blob
*}

{$mode objfpc}
unit mono_blob;
interface

type
  PMonoTypeEnum  = ^MonoTypeEnum;
  MonoTypeEnum =  Longint;
const
  MONO_TYPE_END = $00;
  MONO_TYPE_VOID = $01;
  MONO_TYPE_BOOLEAN = $02;
  MONO_TYPE_CHAR = $03;
  MONO_TYPE_I1 = $04;
  MONO_TYPE_U1 = $05;
  MONO_TYPE_I2 = $06;
  MONO_TYPE_U2 = $07;
  MONO_TYPE_I4 = $08;
  MONO_TYPE_U4 = $09;
  MONO_TYPE_I8 = $0a;
  MONO_TYPE_U8 = $0b;
  MONO_TYPE_R4 = $0c;
  MONO_TYPE_R8 = $0d;
  MONO_TYPE_STRING = $0e;
  MONO_TYPE_PTR = $0f;
  MONO_TYPE_BYREF = $10;
  MONO_TYPE_VALUETYPE = $11;
  MONO_TYPE_CLASS = $12;
  MONO_TYPE_VAR = $13;
  MONO_TYPE_ARRAY = $14;
  MONO_TYPE_GENERICINST = $15;
  MONO_TYPE_TYPEDBYREF = $16;
  MONO_TYPE_I = $18;
  MONO_TYPE_U = $19;
  MONO_TYPE_FNPTR = $1b;
  MONO_TYPE_OBJECT = $1c;
  MONO_TYPE_SZARRAY = $1d;
  MONO_TYPE_MVAR = $1e;
  MONO_TYPE_CMOD_REQD = $1f;
  MONO_TYPE_CMOD_OPT = $20;
  MONO_TYPE_INTERNAL = $21;
  MONO_TYPE_MODIFIER = $40;
  MONO_TYPE_SENTINEL = $41;
  MONO_TYPE_PINNED = $45;
  MONO_TYPE_ENUM = $55;


type
  PMonoMetaTableEnum  = ^MonoMetaTableEnum;
  MonoMetaTableEnum =  Longint;
const
  MONO_TABLE_MODULE = 0;
  MONO_TABLE_TYPEREF = 1;
  MONO_TABLE_TYPEDEF = 2;
  MONO_TABLE_FIELD_POINTER = 3;
  MONO_TABLE_FIELD = 4;
  MONO_TABLE_METHOD_POINTER = 5;
  MONO_TABLE_METHOD = 6;
  MONO_TABLE_PARAM_POINTER = 7;
  MONO_TABLE_PARAM = 8;
  MONO_TABLE_INTERFACEIMPL = 9;
  MONO_TABLE_MEMBERREF = 10;
  MONO_TABLE_CONSTANT = 11;
  MONO_TABLE_CUSTOMATTRIBUTE = 12;
  MONO_TABLE_FIELDMARSHAL = 13;
  MONO_TABLE_DECLSECURITY = 14;
  MONO_TABLE_CLASSLAYOUT = 15;
  MONO_TABLE_FIELDLAYOUT = 16;
  MONO_TABLE_STANDALONESIG = 17;
  MONO_TABLE_EVENTMAP = 18;
  MONO_TABLE_EVENT_POINTER = 19;
  MONO_TABLE_EVENT = 20;
  MONO_TABLE_PROPERTYMAP = 21;
  MONO_TABLE_PROPERTY_POINTER = 22;
  MONO_TABLE_PROPERTY = 23;
  MONO_TABLE_METHODSEMANTICS = 24;
  MONO_TABLE_METHODIMPL = 25;
  MONO_TABLE_MODULEREF = 26;
  MONO_TABLE_TYPESPEC = 27;
  MONO_TABLE_IMPLMAP = 28;
  MONO_TABLE_FIELDRVA = 29;
  MONO_TABLE_UNUSED6 = 30;
  MONO_TABLE_UNUSED7 = 31;
  MONO_TABLE_ASSEMBLY = 32;
  MONO_TABLE_ASSEMBLYPROCESSOR = 33;
  MONO_TABLE_ASSEMBLYOS = 34;
  MONO_TABLE_ASSEMBLYREF = 35;
  MONO_TABLE_ASSEMBLYREFPROCESSOR = 36;
  MONO_TABLE_ASSEMBLYREFOS = 37;
  MONO_TABLE_FILE = 38;
  MONO_TABLE_EXPORTEDTYPE = 39;
  MONO_TABLE_MANIFESTRESOURCE = 40;
  MONO_TABLE_NESTEDCLASS = 41;
  MONO_TABLE_GENERICPARAM = 42;
  MONO_TABLE_METHODSPEC = 43;
  MONO_TABLE_GENERICPARAMCONSTRAINT = 44;
  MONO_TABLE_UNUSED8 = 45;
  MONO_TABLE_UNUSED9 = 46;
  MONO_TABLE_UNUSED10 = 47;
  MONO_TABLE_DOCUMENT = 48;
  MONO_TABLE_METHODBODY = 49;
  MONO_TABLE_LOCALSCOPE = 50;
  MONO_TABLE_LOCALVARIABLE = 51;
  MONO_TABLE_LOCALCONSTANT = 52;
  MONO_TABLE_IMPORTSCOPE = 53;
  MONO_TABLE_ASYNCMETHOD = 54;
  MONO_TABLE_CUSTOMDEBUGINFORMATION = 55;


implementation

end.
